apiVersion: v1
kind: Service
metadata:
  namespace: gof
  name: demo-web-service
spec:
  selector:
    app: demo-web-deployment
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP
